### ISSUE TITLE
Failed authentication

### ISSUE THREAD

**Issue by sagivoulu** [hkiang01/fastapi-keycloak-oidc-auth#1]
I ran the project and I can't get the authentication to work (as specified in the readme file).

after being redirected to the keycloak authentication page, entering the user & password "test" & getting redirected to the /auth page I get a failure when sending the post request to the keycloak server.
The post request that keeps failing has the following information:
method: POST
- url: http://localhost:8080/auth/realms/Clients/protocol/openid-connect/token
- payload: grant_type=authorization_code&code=90fedb75-6615-493f-bd3b-66f6d4f2f4c7.9888d6a9-290c-40ca-8a6f-1aa71a535d6e.1adb3baa-fb7e-4f0c-ab6c-437bd3d71757&redirect_uri=http://localhost:8000/&client_id=app
- headers: {'Content-Type': 'application/x-www-form-urlencoded'}

The post function returns the error:
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /auth/realms/Clients/protocol/openid-connect/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2f78e79890>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by hkiang01** [comment]
You could try iterating through these [network modes](https://docs.docker.com/compose/compose-file/#network_mode) and see what sticks... that might work?

Also, I tried reproducing your error and this is what I got:

POST
- url: http://localhost:8080/auth/realms/Clients/protocol/openid-connect/token
- payload: grant_type=authorization_code&code=202f9eb8-ba63-4fca-80a5-7ff8b8519232.7709902b-1093-48c1-bdb4-09ea9d6f43f8.8c53b20c-9ea0-4871-a1ca-12aadcf77818&redirect_uri=http://localhost:8000/&client_id=app
- headers: {'Content-Type': 'application/x-www-form-urlencoded'}

This is what the logs look like with a little modification:

```
app_1       | INFO: ('127.0.0.1', 47670) - "GET /login HTTP/1.1" 307
auth_1      | 02:33:01,162 WARN  [org.keycloak.services] (default task-1) KC-SERVICES0091: Request is missing scope 'openid' so it's not treated as OIDC, but just pure OAuth2 request.
app_1       | INFO: payload: grant_type=authorization_code&code=740e324a-d7d5-4946-b70b-5cd9de3d6c35.d958b24d-f259-4e3b-8d66-64d64df5ecf0.8c53b20c-9ea0-4871-a1ca-12aadcf77818&redirect_uri=http://localhost:8000/&client_id=app
app_1       | INFO: token_response.headers: {'Connection': 'keep-alive', 'Cache-Control': 'no-store', 'Pragma': 'no-cache', 'Content-Type': 'application/json', 'Content-Length': '2302', 'Date': 'Fri, 20 Dec 2019 02:33:03 GMT'}
app_1       | INFO: token_response.content: b'{"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJDY0xKVXhCTWxkeDFrazEzN0hscUVvSzZVaF9SOFd0Zno5LUtCdDJENlNvIn0.eyJqdGkiOiI2Y2EwMDY4ZS1hYjkzLTRjMmQtYTVkOC04N2U5NzAzZmYzZWUiLCJleHAiOjE1NzY4MDk0ODMsIm5iZiI6MCwiaWF0IjoxNTc2ODA5MTgzLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvYXV0aC9yZWFsbXMvQ2xpZW50cyIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJiNmYwMWMzYi1iZDE4LTQ4MDMtOWE5OS02MjQxZTc4MDI0ZTIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhcHAiLCJhdXRoX3RpbWUiOjE1NzY4MDkxODMsInNlc3Npb25fc3RhdGUiOiJkOTU4YjI0ZC1mMjU5LTRlM2ItOGQ2Ni02NGQ2NGRmNWVjZjAiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHA6Ly9sb2NhbGhvc3Q6ODAwMC9sb2dpbiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoiZW1haWwgcHJvZmlsZSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoidGVzdCJ9.Xh7jvG5xFe02IVB197CyFLIkOXU6LFeaCDX_9CXeBmEjnV5i7AyMKdFxhLHajXMexP0nYy86FGzo-4IwM_TEfk6HRs8_kWwBKO2Fr-vJUwW6G1LdIiGnDkXYGgDCOm2QQZqEVTVA-KoeRxr4MrHPt89vI2VLfim-Q_tIZV22HQ_t-N2A1pKwAriU9hV-EG9Xp3fB6Vn41nQm9jKz-0IEUP4hQe5Z42U9oP1Xld_yDxeEy3--pf5xcXKAO1Dq_xZeTE9il04tNLmofvTzc3weSd3G8RQrLnf6xLLq4_TQlfBi_bhfRrLkjrqkD5ooUBM03LxOcedDWU4WzGErgtalDQ","expires_in":300,"refresh_expires_in":1800,"refresh_token":"eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmMGI4MjBlNi0yNzc1LTQzZjktYmQwMi1kZGE0ZWY5YWUxMmQifQ.eyJqdGkiOiIzZjdkNmQwMC04YTk1LTQwMzEtYThjYy00NDNkNTA3NDg3ZTgiLCJleHAiOjE1NzY4MTA5ODMsIm5iZiI6MCwiaWF0IjoxNTc2ODA5MTgzLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvYXV0aC9yZWFsbXMvQ2xpZW50cyIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hdXRoL3JlYWxtcy9DbGllbnRzIiwic3ViIjoiYjZmMDFjM2ItYmQxOC00ODAzLTlhOTktNjI0MWU3ODAyNGUyIiwidHlwIjoiUmVmcmVzaCIsImF6cCI6ImFwcCIsImF1dGhfdGltZSI6MCwic2Vzc2lvbl9zdGF0ZSI6ImQ5NThiMjRkLWYyNTktNGUzYi04ZDY2LTY0ZDY0ZGY1ZWNmMCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIn0.J6Ojlq-cTZR1s4STvLvY7ansCir4ZqcvwVPMMbBOvwg","token_type":"bearer","not-before-policy":1565839535,"session_state":"d958b24d-f259-4e3b-8d66-64d64df5ecf0","scope":"email profile"}'
app_1       | INFO: ('127.0.0.1', 47670) - "GET /auth?session_state=d958b24d-f259-4e3b-8d66-64d64df5ecf0&code=740e324a-d7d5-4946-b70b-5cd9de3d6c35.d958b24d-f259-4e3b-8d66-64d64df5ecf0.8c53b20c-9ea0-4871-a1ca-12aadcf77818 HTTP/1.1" 307
app_1       | DEBUG: {'jti': '6ca0068e-ab93-4c2d-a5d8-87e9703ff3ee', 'exp': 1576809483, 'nbf': 0, 'iat': 1576809183, 'iss': 'http://localhost:8080/auth/realms/Clients', 'aud': 'account', 'sub': 'b6f01c3b-bd18-4803-9a99-6241e78024e2', 'typ': 'Bearer', 'azp': 'app', 'auth_time': 1576809183, 'session_state': 'd958b24d-f259-4e3b-8d66-64d64df5ecf0', 'acr': '1', 'allowed-origins': ['http://localhost:8000/login'], 'realm_access': {'roles': ['offline_access', 'uma_authorization']}, 'resource_access': {'account': {'roles': ['manage-account', 'manage-account-links', 'view-profile']}}, 'scope': 'email profile', 'email_verified': False, 'preferred_username': 'test'}
app_1       | INFO: ('127.0.0.1', 47670) - "GET / HTTP/1.1" 200
```

Here is said modification:
```python
@app.get("/auth")
async def auth(code: str) -> RedirectResponse:
    payload = (
        f"grant_type=authorization_code&code={code}"
        f"&redirect_uri={APP_BASE_URL}&client_id=app"
    )
    logger.info(f"payload: {payload}")
    headers = {"Content-Type": "application/x-www-form-urlencoded"}
    token_response = requests.request(
        "POST", TOKEN_URL, data=payload, headers=headers
    )
    logger.info(f"token_response.headers: {token_response.headers}")
    logger.info(f"token_response.content: {token_response.content}")
...
```

Here are a few screenshots that indicate how I set up the client, and user in Keycloak. Note that they exist in the `Clients` realm

![app_client](https://user-images.githubusercontent.com/5448093/71225799-6487fe80-229f-11ea-8874-e2d15d5064de.png)

![users](https://user-images.githubusercontent.com/5448093/71225808-6b167600-229f-11ea-8d1d-d10dc9517728.png)

Let me know if that helps!

**Comment by sagivoulu** [comment]
Solved it. the problem was that the fastapi container tried to access keycloak via at the address localhost:8080, but that was not accessible via the fastapi container. solved it by changing the code to accessing http://auth:8080 and adding a link between the two services in the doker-compose file.

I also had an issue because the fastapi container was only listening to request from itself, so I set it to listen to 0.0.0.0.

All of these issues probably are caused by wrong docker networking settings, but im not very proficient in docker networking...

Thanks for the help!

**Comment by sagivoulu** [comment]
B.T.W have you tried using keycloak in fastapi using dependency injection? I found [this](https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/) very nice tutorial on the FastAPI using dependency injection & self generated jwt tokens...

Im gonna try integrating keycloak via a dependency injection, could majorly simplify the code...

**Comment by hkiang01** [comment]
> B.T.W have you tried using keycloak in fastapi using dependency injection? 

yup, in a separate, proprietary project. It goes really well together with [keycloak-gatekeeper](https://github.com/keycloak/keycloak-gatekeeper). You can put this in front of the pod/container you're trying to protect.

(As for this project, I just made it to try something out).

> [Solved it.](https://github.com/hkiang01/fastapi-keycloak-oidc-auth/issues/1#issuecomment-568050293)

closing

**Comment by HedgeShot** [comment]
@hkiang01 
Would you mind sharing your compose file / gatekeeper config?
I could protect the route /docs with gatekeeper but when hitting api endpoints, i have a Bad Gateway error.

@sagivoulu did you manage doing something with dependy injection? I had a look at keycloak-client middleware for starlette but haven't been able to make it run.

Thanks a lot

**Comment by hkiang01** [comment]
@HedgeShot the docker compose file is in the repo. No config was used outside of what is already provided by the jboss/keycloak image.

**Comment by hkiang01** [comment]
@HedgeShot @sagivoulu I would encourage you both to look at this [blog post](https://hkiang01.github.io/kubernetes/keycloak/) describing how to use Keycloak in a more systematic and independent fashion
